### PR TITLE
join command no longer adds players twice

### PR DESCRIPTION
**Pull request by ac15CR**
/hg join will no longer add a player to the same match 2 times.

Also made small linting changes to JoinGameCommand.

### CODE REVIEW

**Review by Ayman-Isam — COMMENTED** [review]
Hey, this is not a stray /, it is in all languages and it's used in the plugin for a message

**Comment by Ayman-Isam** [comment]
The change you made where you fixed players joining did not fix the issue, the issue is caused by removing player from the spawnpoint list of a world after teleporting instead of before teleporting, I've fixed the issue and planning to deploy a fix soon

**Comment by ac15CR** [comment]
> The change you made where you fixed players joining did not fix the issue, the issue is caused by removing player from the spawnpoint list of a world after teleporting instead of before teleporting, I've fixed the issue and planning to deploy a fix soon

Interesting, when I rebuilt the jar and tested it players were no longer being double counted. Also that function seemed to add the player to a new spawnpoint so to me it fit that would cause the double counting.

> Hey, this is not a stray /, it is in all languages and it's used in the plugin for a message

I wasn't sure and thought that may be part of the normal languages as well but was following #14. Also came across that bug on my first launch and after removing the "/" the plugin loaded correctly. I'm sure there is definitely a better solution to that though.

**Comment by Ayman-Isam** [comment]
> Interesting, when I rebuilt the jar and tested it players were no longer being double counted. Also that function seemed to add the player to a new spawnpoint so to me it fit that would cause the double counting.

That may have fixed the issue but it would cause issues while switching to maps that have already been created because then it would not assign spawnpoints to players

As for #14, it has been fixed already

**Pull request closed without merging**
